[package]
name = "perf-tools"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gen_payload"
path = "gen_payload.rs"

[[bin]]
name = "simple_benchmark"
path = "simple_benchmark.rs"

[dependencies]
serde_json = "1.0"
rand = "0.8"
clap = { version = "4.0", features = ["derive"] }
